[package]
name = "python_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "python_rust_lib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }

