[project]
name = "python-rust"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
]

[build-system]
requires = ["meson-python"]
build-backend = "mesonpy"

#[build-system]
#requires = ["maturin>=1,<2"]
#build-backend = "maturin"
# `pip install .` works with the maturin build backend